apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-watchlist
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fullstackjam/flask-watchlist.git
    path: helm/flask-watchlist
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
