- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - prerequisites
    - k3s

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium

- name: Install argocd
  hosts: localhost
  roles:
    - argocd
