all:
  vars:
    control_plane_endpoint: 192.168.2.110
    load_balancer_ip_pool:
      - 192.168.2.188/30
metal:
  children:
    masters:
      hosts:
        master: {ansible_host: 192.168.2.110}
    workers:
      hosts:
        worker1: {ansible_host: 192.168.2.111}
        worker2: {ansible_host: 192.168.2.112}
