---
- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace }}"
    state: present

- name: Check if this is the first installation
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app.kubernetes.io/instance={{ argocd_instance_name }}
    field_selectors:
      - status.phase=Running
  register: first_install

- name: Render ArgoCD manifests from Helm chart
  kubernetes.core.helm_template:
    chart_ref: "{{ argocd_chart_path }}"
    include_crds: true
    release_name: "{{ argocd_release_name }}"
    release_namespace: "{{ argocd_namespace }}"
    dependency_update: true
    values_files:
      - "{{ argocd_values_file }}"
  register: argocd_manifests

- name: Apply ArgoCD manifests
  kubernetes.core.k8s:
    resource_definition: "{{ argocd_manifests.stdout }}"
    apply: true
    server_side_apply:
      field_manager: "{{ argocd_field_manager }}"
