---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoally-backend
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/fullstackjam/autoally-backend.git
    path: helm/autoally-backend
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
