woodpecker:
  agent:
    mapAgentSecret: false
    extraSecretNamesForEnvFrom: ["woodpecker-secret"]
  server:
    createAgentSecret: false
    extraSecretNamesForEnvFrom: ["woodpecker-secret"]
    env:
      WOODPECKER_HOST: https://ci.fullstackjam.dev
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://git.fullstackjam.dev
      WOODPECKER_OPEN: true
      WOODPECKER_ADMIN: gitea_admin
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - host: &host ci.fullstackjam.dev
          paths:
            - path: /
      tls:
        - secretName: woodpecker-tls-certificate
          hosts:
            - *host
